name: Timber
version: 1.2.2
main: io.github.mastercash.timber.Main

api-version: 1.15

description: A lumberjack's best friend tree farming just got easier.
load: POSTWORLD
author: Master_Cash
website: github.com/mastercash

softdepend:
- CoreProtect

permissions:
  timber.*:
    description: Allows you to use the plugin.
    children:
      timber.use: true
  timber.use:
    description: Allows you to use the plugin.
    default: true